from enum import StrEnum


class OperatingMode(StrEnum):
    TAKEOFF = "TAKEOFF"
    CLIMB = "CLIMB"
    CRUISE = "CRUISE"
    LOITER = "LOITER"
    DESCENT = "DESCENT"
    LANDING = "LANDING"
    OTHER = "OTHER"


class DegradationScenario(StrEnum):
    NORMAL = "NORMAL"
    COOLING_DEGRADATION = "COOLING_DEGRADATION"
    LUBRICATION_DEGRADATION = "LUBRICATION_DEGRADATION"
    VIBRATION_INCREASE = "VIBRATION_INCREASE"
    SENSOR_DRIFT = "SENSOR_DRIFT"


class HealthStatus(StrEnum):
    NORMAL = "NORMAL"
    WARNING = "WARNING"
    CRITICAL = "CRITICAL"
    NOT_AVAILABLE = "NOT_AVAILABLE"


class EventSeverity(StrEnum):
    INFO = "INFO"
    WARNING = "WARNING"
    CRITICAL = "CRITICAL"


class EventStatus(StrEnum):
    ACTIVE = "ACTIVE"
    RESOLVED = "RESOLVED"
    INFO = "INFO"


class AnalysisType(StrEnum):
    ANOMALY_DETECTION = "ANOMALY_DETECTION"
    FAULT_CLASSIFICATION = "FAULT_CLASSIFICATION"
    DEGRADATION_ESTIMATION = "DEGRADATION_ESTIMATION"
    RUL_ESTIMATION = "RUL_ESTIMATION"
    PREDICTIVE_MAINTENANCE = "PREDICTIVE_MAINTENANCE"
    EXPLAINABILITY = "EXPLAINABILITY"


class ReliabilityStatus(StrEnum):
    AVAILABLE = "AVAILABLE"
    NOT_AVAILABLE = "NOT_AVAILABLE"


class DataQuality(StrEnum):
    VALID = "VALID"
    INVALID = "INVALID"
    MISSING = "MISSING"
    DUPLICATE = "DUPLICATE"
    OUT_OF_ORDER = "OUT_OF_ORDER"
